# Generated by Django 6.0.8 on 2026-08-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code barre')),
                ('short_description', models.TextField(blank=True, verbose_name='Courte description')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name="Date d'entrée")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='oeuvres/covers/', verbose_name='Image de couverture')),
                ('content_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Oeuvre',
                'verbose_name_plural': 'Oeuvres',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Type de jeu',
                'verbose_name_plural': 'Types de jeu',
            },
        ),
        migrations.CreateModel(
            name='PlayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Mode de jeu',
                'verbose_name_plural': 'Modes de jeu',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('oeuvre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.oeuvre')),
                ('author', models.CharField(max_length=255, verbose_name='Auteur')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('nb_pages', models.PositiveIntegerField(verbose_name='Nombre de pages')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='Éditeur')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
            bases=('core.oeuvre',),
        ),
        migrations.CreateModel(
            name='Lent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(db_index=True, verbose_name="Date d'emprunt")),
                ('date_out', models.DateField(verbose_name='Date de retour')),
                ('borrower', models.CharField(max_length=30, verbose_name='Emprunteur')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('returned', models.BooleanField(default=False, verbose_name='Rendu')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.oeuvre', verbose_name='Oeuvre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('oeuvre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.oeuvre')),
                ('min_age', models.PositiveIntegerField(default=0, verbose_name='Âge minimum')),
                ('players_min', models.PositiveIntegerField(default=0, verbose_name='Nombre de joueurs minimum')),
                ('players_max', models.PositiveIntegerField(default=0, verbose_name='Nombre de joueurs maximum')),
                ('weight_grams', models.PositiveIntegerField(verbose_name='Poids en état (grammes)')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile'), (4, 'Expert')], verbose_name='Difficulté')),
                ('play_time', models.PositiveIntegerField(default=0, verbose_name='Temps de jeu (minutes)')),
                ('is_legacy', models.BooleanField(default=False, verbose_name='Legacy')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (état et pièces manquantes)')),
                ('box_content', models.TextField(blank=True, verbose_name='Contenue de la boite')),
                ('space', models.CharField(choices=[('INDOOR', 'Intérieur (Jeu de société)'), ('OUTDOOR', 'Extérieur')], default='INDOOR', max_length=10, verbose_name='Espace')),
                ('game_types', models.ManyToManyField(blank=True, related_name='games', to='core.gametype', verbose_name='Types')),
                ('play_modes', models.ManyToManyField(blank=True, related_name='games', to='core.playmode', verbose_name='Modes de jeu')),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
            bases=('core.oeuvre',),
        ),
    ]
