# Generated by Django 6.0.8 on 2026-08-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeuvre',
            name='short_description',
            field=models.TextField(blank=True, max_length=635, verbose_name='Courte description'),
        ),
    ]
