# Generated by Django 6.0.8 on 2026-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_oeuvre_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cabinet_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Couleur armoire (Hex)'),
        ),
        migrations.AddField(
            model_name='game',
            name='video_rules_url',
            field=models.URLField(blank=True, null=True, verbose_name='Vidéo des règles (URL)'),
        ),
    ]
