# Generated by Django 6.0.8 on 2026-08-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_cabinet_color_game_video_rules_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='video_rules_url',
        ),
        migrations.AddField(
            model_name='game',
            name='video_youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Vidéo YouTube'),
        ),
    ]
