# Generated by Django 6.0.8 on 2026-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_game_video_rules_url_game_video_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom (ex: Armoire A)')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Couleur (Hex)')),
            ],
            options={
                'verbose_name': "Couleur d'armoire",
                'verbose_name_plural': "Couleurs d'armoire",
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='cabinet_color',
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='cabinet_colors',
            field=models.ManyToManyField(blank=True, related_name='oeuvres', to='core.cabinetcolor', verbose_name="Couleurs d'armoire"),
        ),
    ]
