# Generated by Django 6.0.8 on 2026-08-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cabinetcolor_remove_game_cabinet_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oeuvre',
            name='cabinet_colors',
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='cabinet_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeuvres', to='core.cabinetcolor', verbose_name="Couleur d'armoire"),
        ),
    ]
