# Generated by Django 6.0.8 on 2026-08-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_oeuvre_cabinet_colors_oeuvre_cabinet_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='notes',
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='notes',
            field=models.TextField(blank=True, max_length=380, verbose_name="Notes de l'équipe"),
        ),
    ]
