# Generated by Django 6.0.8 on 2026-08-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lent_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='space',
        ),
    ]
